[package]
name = "backend2"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.104", features = ["backtrace"] }
axum = { version = "0.8.9", features = ["macros", "ws"] }
log = { version = "0.4.33", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
simple_logger = "5.2.0"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.53.1", features = ["full"] }
uuid = { version = "1.24.0", features = ["serde", "v4"] }
